data:
  source_cloud_path: 'KITTI/2011_09_26/2011_09_26_drive_0011_sync/velodyne_points/data/pcd/0000000000.pcd'
  target_cloud_path: 'KITTI/2011_09_26/2011_09_26_drive_0011_sync/velodyne_points/data/pcd/0000000002.pcd'
  format: 'auto'
  voxel_downsample: True
  voxel_size: 0.7
bayes_opt:
  #General
  #Type: rotation only (rotation), translation only(translation), combined (all), rotation than translation=(separate)
  type: separate
  #Initial Random Guesses
  init_count: 20
  #Number of iterations
  num_iter: 35
  #parameter bounds
  parameter_bounds:
    x:
    - -4.0
    - 4.0
    y:
    - -2.0
    - 2.0
    z:
    - -1.0
    - 1.0
    roll:
    - -3.1416
    - 3.1416
    pitch:
    - -3.1416
    - 3.1416
    yaw:
    - -3.1416
    - 3.1416
  #Acquisition function (Upper confidence bound (ucb))
  acq: ei
  #Error metric
  error_metric: 'distance'
  #Upper confidence Bound
  kappa: 0.1
  #Expected Improvement
  xi: 1.0e-4
  #Probability of Improvement
  alpha: 1.0e-5
icp:
  threshold: 0.02
  max_iterations: 10000
  relative_fitness: 1.0e-10
  relative_rmse: 1.0e-10


